ci:
    autoupdate_commit_msg: '[automated] pre-commit autoupdate'
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
        language: system
        language_version: python3
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
